name: base
channels:
  - pytorch
  - alubbock
  - conda-forge
  - dglteam
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py37_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - alabaster=0.7.12=py37_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py37_0
  - anaconda-navigator=1.9.12=py37_0
  - anaconda-project=0.8.4=py_0
  - argh=0.26.2=py37_0
  - asn1crypto=1.3.0=py37_0
  - astroid=2.3.3=py37_0
  - astropy=4.0=py37he774522_0
  - atomicwrites=1.3.0=py37_1
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.1.7=py37he774522_0
  - beautifulsoup4=4.8.2=py37_0
  - bitarray=1.2.1=py37he774522_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - blosc=1.16.3=h7bd577a_0
  - bokeh=1.4.0=py37_0
  - boto=2.49.0=py37_0
  - bottleneck=1.3.2=py37h2a96729_0
  - brotlipy=0.7.0=py37he774522_1000
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.4.13=haa95532_1
  - certifi=2020.12.5=py37haa95532_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.3.0=py_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.3=py_0
  - comtypes=1.1.7=py37_0
  - conda=4.10.1=py37haa95532_1
  - conda-build=3.18.11=py37_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.6.0=py37h62dcd97_0
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - contextlib2=0.6.0.post1=py_0
  - cryptography=2.8=py37h7a1dbc1_0
  - cudatoolkit=11.0.221=h74a9793_0
  - curl=7.68.0=h2a8f88b_0
  - cycler=0.10.0=py37_0
  - cython=0.29.15=py37ha925a31_0
  - cytoolz=0.10.1=py37he774522_0
  - dask=2.11.0=py_0
  - dask-core=2.11.0=py_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dgl=0.5.2=py37_0
  - dgl-cuda10.2=0.5.2=py37_0
  - diff-match-patch=20181111=py_0
  - distributed=2.11.0=py37_0
  - docutils=0.16=py37_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - fastcache=1.1.0=py37he774522_0
  - ffmpeg=4.2.3=ha925a31_0
  - filelock=3.0.12=py_0
  - flake8=3.7.9=py37_0
  - freetype=2.9.1=ha9979f8_1
  - fsspec=0.6.2=py_0
  - future=0.18.2=py37_0
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=1.4.0=py37he774522_0
  - glob2=0.7=py_0
  - gmpy2=2.0.8=py37h0964b28_3
  - graphviz=2.41=0
  - greenlet=0.4.15=py37hfa6e2cd_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py37_0
  - hypothesis=5.5.4=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2020.0=166
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jdcal=1.4.1=py_0
  - jedi=0.14.1=py37_0
  - jpeg=9d=he774522_0
  - json5=0.9.1=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=21.1.0=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - krb5=1.17.1=hc04afaa_0
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libarchive=3.3.3=h0643e63_5
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.68.0=h2a8f88b_0
  - libiconv=1.15=h1df5818_7
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - liblief=0.9.0=ha925a31_2
  - libllvm9=9.0.1=h21ff451_0
  - libopencv=4.4.0=py37_2
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.1.0=h56a325e_0
  - libuv=1.40.0=he774522_0
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - llvmlite=0.31.0=py37ha925a31_0
  - locket=0.2.0=py37_1
  - lxml=4.5.0=py37h1350720_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - mccabe=0.6.1=py37_1
  - menuinst=1.4.16=py37he774522_0
  - mistune=0.8.4=py37he774522_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - mock=4.0.1=py_0
  - more-itertools=8.2.0=py_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.1.0=py37_0
  - msgpack-python=1.0.2=py37h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py37_0
  - navigator-updater=0.2.1=py37_0
  - nltk=3.4.5=py37_0
  - nose=1.3.7=py37_2
  - notebook=6.0.3=py37_0
  - numba=0.48.0=py37h47e9c7a_0
  - numexpr=2.7.1=py37h25d0782_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py37_0
  - opencv=4.4.0=py37_2
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1k=h2bbff1b_0
  - pandas=1.2.4=py37hd77b12b_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.3=py37haa95532_1
  - paramiko=2.7.1=py_0
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - path=13.1.0=py37_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py37_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py37_0
  - pep8=1.7.1=py37_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - pkginfo=1.5.0.1=py37_0
  - pluggy=0.13.1=py37_0
  - ply=3.11=py37_0
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - psutil=5.6.7=py37he774522_0
  - py=1.8.1=py_0
  - py-lief=0.9.0=py37ha925a31_2
  - py-opencv=4.4.0=py37h43977f1_2
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3=py37he774522_0
  - pycparser=2.20=py_2
  - pycrypto=2.6.1=py37hfa6e2cd_9
  - pycurl=7.43.0.5=py37h7a1dbc1_0
  - pydocstyle=4.0.1=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py37_0
  - pynacl=1.3.0=py37h62dcd97_0
  - pyodbc=4.0.30=py37ha925a31_0
  - pyopengl=3.1.1a1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1
  - pyrsistent=0.15.7=py37he774522_0
  - pysocks=1.7.1=py37_0
  - pytables=3.6.1=py37h1da0976_0
  - pytest=5.3.5=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.8.0=py_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.7=py37_0
  - python-libarchive-c=2.8=py37_13
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37he774522_0
  - pywin32=227=py37he774522_1
  - pywin32-ctypes=0.2.0=py37_1000
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3=py37he774522_0
  - pyzmq=18.1.1=py37ha925a31_0
  - qdarkstyle=2.8=py_0
  - qt=5.12.5=h7ef1ec2_0
  - qtawesome=0.6.1=py_0
  - qtconsole=4.6.0=py_1
  - qtpy=1.9.0=py_0
  - requests=2.22.0=py37_1
  - rope=0.16.0=py_0
  - rtree=0.9.3=py37h21ff451_0
  - ruamel_yaml=0.15.87=py37he774522_0
  - scikit-image=0.16.2=py37h47e9c7a_0
  - scikit-learn=0.22.1=py37h6288b17_0
  - send2trash=1.5.0=py37_0
  - setuptools=45.2.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37h6538335_0
  - snappy=1.1.7=h777316e_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py37_0
  - sortedcontainers=2.1.0=py37_0
  - soupsieve=1.9.5=py37_0
  - sphinx=2.4.0=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.2.0=py_0
  - spyder=4.0.1=py37_0
  - spyder-kernels=1.8.1=py37_0
  - sqlalchemy=1.3.13=py37he774522_0
  - sqlite=3.31.1=he774522_0
  - statsmodels=0.11.0=py37he774522_0
  - swig=3.0.12=h047fa9f_3
  - tbb=2020.0=h74a9793_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.8=hfa6e2cd_0
  - toml=0.10.1=py_0
  - toolz=0.10.0=py_0
  - torchaudio=0.7.0=py37
  - torchvision=0.8.1=py37_cu110
  - tornado=6.0.3=py37he774522_3
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37he774522_0
  - typing_extensions=3.7.4.2=py_0
  - ujson=1.35=py37hfa6e2cd_0
  - unicodecsv=0.14.1=py37_0
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - watchdog=0.10.2=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.0=py_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - win_unicode_console=0.5=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37he774522_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.2.7=py_0
  - xlwings=0.17.1=py37_0
  - xlwt=1.3.0=py37_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=h33f27b4_3
  - zict=1.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zope=1.0=py37_1
  - zope.event=4.4=py37_0
  - zope.interface=4.7.1=py37he774522_0
  - zstd=1.3.7=h508b16e_0
  - pip:
    - absl-py==0.12.0
    - adal==1.2.5
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - appdirs==1.4.4
    - applicationinsights==0.11.9
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - autonomous-learning-library==0.5.3
    - azure-common==1.1.26
    - azure-core==1.9.0
    - azure-graphrbac==0.61.1
    - azure-identity==1.4.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-resource==12.0.0
    - azure-mgmt-storage==11.2.0
    - azureml==0.2.7
    - azureml-automl-core==1.19.0
    - azureml-core==1.19.0
    - azureml-dataprep==2.6.3
    - azureml-dataprep-native==26.0.0
    - azureml-dataprep-rslex==1.4.0
    - azureml-dataset-runtime==1.19.0.post1
    - azureml-pipeline==1.19.0
    - azureml-pipeline-core==1.19.0
    - azureml-pipeline-steps==1.19.0
    - azureml-sdk==1.19.0
    - azureml-telemetry==1.19.0
    - azureml-train==1.19.0
    - azureml-train-automl-client==1.19.0
    - azureml-train-core==1.19.0
    - azureml-train-restclients-hyperdrive==1.19.0
    - bleach==3.2.2
    - blessings==1.7
    - box2d-py==2.3.8
    - cached-property==1.5.2
    - cachetools==4.1.0
    - cffi==1.14.4
    - clldutils==3.5.4
    - colorful==0.5.4
    - colorlog==4.4.0
    - comcrawl==1.0.2
    - csvw==1.8.0
    - dataclasses==0.6
    - datasets==1.3.0
    - deap==1.3.1
    - deepspeed==0.3.10
    - dill==0.3.3
    - distro==1.5.0
    - docker==4.4.1
    - dotnetcore2==2.1.20
    - easyprocess==0.3
    - fire==0.3.1
    - flask==1.1.2
    - flask-login==0.5.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==0.14.3
    - flatbuffers==1.12
    - func-timeout==4.3.5
    - fusepy==3.0.1
    - gast==0.4.0
    - gin-config==0.1.3
    - google-api-core==1.25.1
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - gplearn==0.4.1
    - gpustat==0.6.0
    - grpcio==1.34.1
    - gym==0.10.11
    - h5py==3.1.0
    - hiredis==1.1.0
    - huggingface-hub==0.0.2
    - idna==2.8
    - imageio==2.4.0
    - invoke==1.5.0
    - ipython==7.19.0
    - isodate==0.6.0
    - jeepney==0.6.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==1.0.0
    - jsonform==0.0.2
    - jsonpickle==1.4.2
    - jsonsir==0.0.2
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - mpi4py==3.0.3
    - msal==1.8.0
    - msal-extensions==0.2.2
    - msrest==0.6.19
    - msrestazure==0.6.4
    - multidict==5.1.0
    - multiprocess==0.70.11.1
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - ndg-httpsclient==0.5.1
    - nest-asyncio==1.4.3
    - networkx==2.5
    - ninja==1.10.0.post2
    - nlp==0.4.0
    - numpy==1.18.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - opencv-python==4.3.0.36
    - openslide-python==1.1.2
    - opt-einsum==3.2.1
    - packaging==20.8
    - parsivar==0.2.3
    - pathlib==1.0.1
    - pathspec==0.8.1
    - pdf2image==1.12.1
    - pdfminer-six==20201018
    - peppercorn==0.6
    - pgmpy==0.1.12
    - portalocker==1.7.1
    - prettytable==0.7.2
    - proged==0.8.4
    - prompt-toolkit==3.0.13
    - protobuf==3.12.1
    - py-spy==0.3.4
    - pyarrow==1.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==2.8.5
    - pycairo==1.20.0
    - pyelftools==0.27
    - pyglet==1.3.2
    - pyjwt==1.7.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytesseract==0.3.3
    - python-docx==0.8.10
    - python-dotenv==0.15.0
    - python-easyconfig==0.1.7
    - python-igraph==0.8.3
    - pytorch-lightning==0.7.6
    - pyvirtualdisplay==1.3
    - ray==1.1.0
    - redis==3.5.3
    - regex==2019.04.14
    - requests-file==1.5.1
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - resource==0.2.1
    - rfc3986==1.4.0
    - rsa==4.0
    - ruamel-yaml==0.16.12
    - ruamel-yaml-clib==0.2.2
    - sacremoses==0.0.43
    - scipy==1.6.3
    - seaborn==0.11.1
    - secretstorage==3.3.0
    - segments==2.1.3
    - sentence-transformers==0.3.6
    - sentencepiece==0.1.91
    - six==1.15.0
    - sklearn==0.0
    - sympy==1.7.1
    - ta==0.7.0
    - ta-lib==0.4.19
    - tabulate==0.8.7
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==1.8
    - tensorflow==2.5.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu-estimator==2.3.0
    - tensorflow-probability==0.10.0
    - termcolor==1.1.0
    - texttable==1.6.3
    - tf-agents==0.4.0
    - tokenizers==0.10.1
    - torch==1.8.1+cu111
    - torch-nightly==1.0.0.dev20190325
    - tqdm==4.49.0
    - transformers==4.2.2
    - uritemplate==3.0.1
    - websocket-client==0.57.0
    - wheel==0.36.2
    - wrapt-timeout-decorator==1.3.1
    - wtforms==2.3.3
    - xxhash==2.0.0
    - yarl==1.6.3
    - zeep==4.0.0
prefix: C:\Users\vpcom\Anaconda3
